add None value for cache extension
niwinz/django-jinja pull request #274
Opened 2021-03-10 19:04 UTC by romanyakovlev

As Django docs said [The fragment is cached forever if timeout is None](https://docs.djangoproject.com/en/3.1/topics/cache/#template-fragment-caching). However when I set timeout to None get this error:
`"cache" tag got a non-integer timeout value: None`. So I made a little fix.

2021-03-11 07:07 UTC, auvipy requested changes
can you also add a test to very the change?

2021-03-14 14:32 UTC, wizpig64 commented
It looks like this change is much like the one in django 2.0 from four years ago, that allowed a None timeout:

* https://github.com/django/django/pull/8120 
* https://code.djangoproject.com/ticket/27882

So this gets approval from me. I contributed a test and added a line in the changelog.

2021-03-14 15:17 UTC, auvipy approved these changes

2021-03-21 20:06 UTC, wizpig64 commented
hmm, i thought that doing it that way would have merged this PR as well, but maybe it didn't because the merge was done with a rebase. @auvipy could you merge or close this?

2021-03-22 04:15 UTC, auvipy commented
the commit is merged

2021-03-22 04:15 UTC, closed without merging